const TYPE_FILTERED_LIST_LOADING = 'TYPE_FILTERED_LIST_LOADING';
const TYPE_FILTERED_LIST_SUCCESS = 'TYPE_FILTERED_LIST_SUCCESS';
const TYPE_FILTERED_LIST_FAILURE = 'TYPE_FILTERED_LIST_FAILURE';

export {
    TYPE_FILTERED_LIST_LOADING,
    TYPE_FILTERED_LIST_SUCCESS,
    TYPE_FILTERED_LIST_FAILURE,
}