const POKEMON_PAGE_LOADING = 'POKEMON_PAGE_LOADING';
const POKEMON_PAGE_SUCCESS = 'POKEMON_PAGE_SUCCESS';
const POKEMON_PAGE_FAILURE = 'POKEMON_PAGE_FAILURE';

export {
    POKEMON_PAGE_LOADING,
    POKEMON_PAGE_SUCCESS,
    POKEMON_PAGE_FAILURE
}