export const POKEMON_LIST_LOADING = 'POKEMON_LIST_LOADING';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAILURE = 'POKEMON_LIST_FAILURE';
export const POKEMON_LIST_SEARCH  = 'POKEMON_LIST_SEARCH';
export const CLEAN_SEARCH         = 'CLEAN_SEARCH';